name: Issue assignment

on:
    issues:
        types: [opened, labeled]

jobs:
  auto-assign:
    if: github.event.label.name == 'accelerate_candidate'
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          # teams: rax-incubate/incubate-maintainers
          assignees: mrc0der, mbordash2
          numOfAssignee: 2
          allowSelfAssign: true